# Generated by Django 5.2.1 on 2025-05-28 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carreras',
            new_name='Carrera',
        ),
        migrations.RenameModel(
            old_name='Materias',
            new_name='Materia',
        ),
    ]
