# Generated by Django 5.2.1 on 2025-06-19 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formbuilder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='creado',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='estructura',
        ),
        migrations.AddField(
            model_name='formulario',
            name='fields',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='respuestaformulario',
            name='formulario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='formbuilder.formulario'),
        ),
    ]
