# Generated by Django 5.2.1 on 2025-09-29 08:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formbuilder', '0002_remove_formulario_creado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formulario',
            options={'ordering': ['-fecha_modificacion']},
        ),
        migrations.AddField(
            model_name='formulario',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el formulario está activo y puede recibir respuestas'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='formulario',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
