# Generated by Django 5.2.1 on 2025-06-30 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_importer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloAutorizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(default=None, max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='ModeloImportable',
        ),
    ]
