# Generated by Django 5.2.1 on 2025-06-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_importer', '0002_modeloautorizado_delete_modeloimportable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeloautorizado',
            name='app_label',
        ),
        migrations.RemoveField(
            model_name='modeloautorizado',
            name='model_name',
        ),
        migrations.AddField(
            model_name='modeloautorizado',
            name='nombre_app',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='modeloautorizado',
            name='nombre_modelo',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
