# Generated by Django 5.2.1 on 2025-07-09 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloAutorizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_app', models.CharField(max_length=100)),
                ('nombre_modelo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PlantillaWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to='plantillas_word/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('modelo_autorizado', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='docsbuilder.modeloautorizado')),
            ],
        ),
        migrations.CreateModel(
            name='MapeoVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('simple', 'Campo simple'), ('especial', 'Campo especial'), ('tabla', 'Tabla dinámica')], default='simple', max_length=20)),
                ('campo_modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('especial', models.CharField(blank=True, max_length=50, null=True)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapeos', to='docsbuilder.plantillaword')),
            ],
        ),
    ]
