# Generated by Django 5.2.1 on 2025-07-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsbuilder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapeovariable',
            name='campo_modelo',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
