# Generated by Django 5.2.1 on 2025-07-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsbuilder', '0002_alter_mapeovariable_campo_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapeovariable',
            name='especial',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
