# Generated by Django 5.2.1 on 2025-07-09 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsbuilder', '0003_alter_mapeovariable_especial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to='plantillas/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='plantillaword',
            name='modelo_autorizado',
        ),
        migrations.CreateModel(
            name='VariablePlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('simple', 'Simple'), ('especial', 'Especial'), ('tabla', 'Tabla/Lista')], default='simple', max_length=20)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='docsbuilder.plantilla')),
            ],
        ),
        migrations.DeleteModel(
            name='MapeoVariable',
        ),
        migrations.DeleteModel(
            name='ModeloAutorizado',
        ),
        migrations.DeleteModel(
            name='PlantillaWord',
        ),
    ]
