# Generated by Django 5.2.1 on 2025-07-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsbuilder', '0004_plantilla_remove_plantillaword_modelo_autorizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variableplantilla',
            name='campo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='variableplantilla',
            name='especial_opcion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='variableplantilla',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
