# Generated by Django 5.2.1 on 2025-07-11 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docsbuilder', '0005_variableplantilla_campo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variableplantilla',
            name='modelo',
        ),
    ]
