# Generated by Django 5.2.1 on 2025-07-08 19:14

import datos_academicos.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMateria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trámite',
                'verbose_name_plural': 'Trámites',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('apellido_materno', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('semestre', models.IntegerField(default=1)),
                ('promedio', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('modalidad', models.CharField(choices=[('A', 'A (Presencial)'), ('B', 'B (Sabatino)')], default='A', max_length=20)),
                ('estatus', models.CharField(choices=[('Inscrito', 'Inscrito'), ('No Inscrito', 'No Inscrito'), ('Titulado', 'Titulado'), ('Baja definitiva', 'Baja definitiva'), ('Baja temporal', 'Baja temporal')], default='Inscrito', max_length=20)),
                ('division_estudio', models.CharField(choices=[('Nuevo Ingreso', 'Nuevo Ingreso'), ('Reingreso', 'Reingreso'), ('Convalidación', 'Convalidación'), ('Traslado', 'Traslado'), ('Equivalencia', 'Equivalencia')], default='Nuevo Ingreso', max_length=50)),
                ('fecha_ingreso', models.DateField(blank=True, default=None, null=True)),
                ('curp', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True)),
                ('estado_civil', models.CharField(blank=True, choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Viudo', 'Viudo')], max_length=20, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('nss', models.CharField(blank=True, null=True, unique=True)),
                ('calle', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_exterior', models.CharField(blank=True, max_length=10, null=True)),
                ('numero_interior', models.CharField(blank=True, max_length=10, null=True)),
                ('colonia', models.CharField(blank=True, max_length=100, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=5, null=True)),
                ('zona_procedencia', models.CharField(choices=[('Urbana', 'Urbana'), ('Rural', 'Rural')], max_length=100, null=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='datos_academicos.carrera')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CicloEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.CharField(choices=[('Febrero - Julio', 'Febrero - Julio'), ('Agosto - Diciembre', 'Agosto - Diciembre')], default=None, max_length=50)),
                ('año', models.IntegerField(default=datos_academicos.models.año_actual, validators=[django.core.validators.MinValueValidator(2004), django.core.validators.MaxValueValidator(datos_academicos.models.año_actual)])),
            ],
            options={
                'unique_together': {('ciclo', 'año')},
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('creditos', models.IntegerField()),
                ('unidades', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(8)])),
                ('horas_teoria', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('horas_practica', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='datos_academicos.carrera')),
                ('tipo', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='datos_academicos.tipomateria')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(blank=True, max_length=50, null=True)),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('materias', models.ManyToManyField(related_name='docentes', to='datos_academicos.materia')),
            ],
        ),
        migrations.CreateModel(
            name='PlanEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(default=None, max_length=20, unique=True)),
                ('plan', models.CharField(default=None, max_length=100)),
                ('carrera', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planes_estudios', to='datos_academicos.carrera')),
                ('materias', models.ManyToManyField(blank=True, null=True, related_name='planes_estudios', to='datos_academicos.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.IntegerField(default=1, help_text='Semestre del grupo', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(19)])),
                ('modalidad', models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', help_text='Modalidad del grupo', max_length=1)),
                ('carrera', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='datos_academicos.carrera')),
            ],
            options={
                'unique_together': {('carrera', 'semestre', 'modalidad')},
            },
        ),
    ]
