# Generated by Django 5.2.1 on 2025-07-10 06:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_academicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cicloescolar',
            name='fecha_fin',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='cicloescolar',
            name='fecha_inicio',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='cicloescolar',
            name='fin_vacaciones',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='cicloescolar',
            name='inicio_vacaciones',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='datos_academicos.alumno')),
                ('ciclo_escolar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='datos_academicos.cicloescolar')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='datos_academicos.materia')),
            ],
            options={
                'ordering': ['alumno', 'materia', 'ciclo_escolar'],
                'unique_together': {('alumno', 'materia', 'ciclo_escolar')},
            },
        ),
    ]
