# Generated by Django 5.2.1 on 2025-07-10 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos_academicos', '0003_alter_calificacion_calificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planestudio',
            name='materias',
        ),
    ]
