# Generated by Django 5.2.1 on 2025-07-10 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos_academicos', '0004_remove_planestudio_materias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planestudio',
            options={'ordering': ['clave'], 'verbose_name': 'Plan de Estudio', 'verbose_name_plural': 'Planes de Estudio'},
        ),
    ]
