# Generated by Django 5.2.1 on 2025-07-10 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_academicos', '0005_alter_planestudio_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='plan_estudio',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='datos_academicos.planestudio'),
        ),
    ]
