# Generated by Django 5.2.1 on 2025-07-10 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos_academicos', '0006_carrera_plan_estudio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planestudio',
            old_name='plan',
            new_name='año',
        ),
    ]
