# Generated by Django 5.2.1 on 2025-07-10 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_academicos', '0007_rename_plan_planestudio_año'),
    ]

    operations = [
        migrations.AddField(
            model_name='planestudio',
            name='creditos',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(400)]),
        ),
    ]
