# Generated by Django 5.2.1 on 2025-07-11 04:24

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_academicos', '0009_alumno_plan_estudio'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='creditos_aprobados',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(400)]),
        ),
        migrations.AddField(
            model_name='alumno',
            name='creditos_totales',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(400)]),
        ),
        migrations.AddField(
            model_name='alumno',
            name='fin_semestre',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='fin_vacaciones',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='inicio_semestre',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='inicio_vacaciones',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
