# Generated by Django 5.2.1 on 2025-07-11 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_academicos', '0010_alumno_creditos_aprobados_alumno_creditos_totales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='fecha_ingreso',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
