# Generated by Django 5.2.1 on 2025-07-16 04:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_academicos', '0011_alter_alumno_fecha_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='acreditacion',
            field=models.CharField(choices=[('Ordinario', 'Ordinario'), ('Convalidación', 'Convalidación')], default='Ordinario', max_length=20),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='creditos',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
