# Generated by Django 5.2.1 on 2025-08-07 00:27

import datos_academicos.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_academicos', '0013_materia_semestre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calificacion',
            options={'ordering': ['alumno', 'materia', 'periodo_escolar']},
        ),
        migrations.CreateModel(
            name='PeriodoEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.CharField(choices=[('Enero - Julio', 'Enero - Julio'), ('Agosto - Diciembre', 'Agosto - Diciembre')], default=None, max_length=50)),
                ('año', models.IntegerField(default=datos_academicos.models.año_actual, validators=[django.core.validators.MinValueValidator(2004), django.core.validators.MaxValueValidator(datos_academicos.models.año_actual)])),
                ('fecha_inicio', models.DateField(blank=True, default=None, null=True)),
                ('fecha_fin', models.DateField(blank=True, default=None, null=True)),
                ('inicio_vacaciones', models.DateField(blank=True, default=None, null=True)),
                ('fin_vacaciones', models.DateField(blank=True, default=None, null=True)),
            ],
            options={
                'unique_together': {('ciclo', 'año')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='periodo_escolar',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='datos_academicos.periodoescolar'),
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together={('alumno', 'materia', 'periodo_escolar')},
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='ciclo_escolar',
        ),
        migrations.DeleteModel(
            name='CicloEscolar',
        ),
    ]
