# Generated by Django 5.2.1 on 2025-08-07 01:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_academicos', '0014_alter_calificacion_options_periodoescolar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodoescolar',
            name='año',
            field=models.IntegerField(default=2025, validators=[django.core.validators.MinValueValidator(2004), django.core.validators.MaxValueValidator(2035)]),
        ),
        migrations.AlterField(
            model_name='periodoescolar',
            name='ciclo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='periodoescolar',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='periodoescolar',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='periodoescolar',
            name='fin_vacaciones',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='periodoescolar',
            name='inicio_vacaciones',
            field=models.DateField(blank=True, null=True),
        ),
    ]
