# Generated by Django 5.2.1 on 2025-08-07 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_academicos', '0015_alter_periodoescolar_año_alter_periodoescolar_ciclo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValoresPorDefectoPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_periodo', models.CharField(default='Personalizado', max_length=100)),
                ('duracion_meses', models.PositiveIntegerField(default=6)),
                ('vacaciones_inicio_dias', models.PositiveIntegerField(default=1)),
                ('vacaciones_duracion_dias', models.PositiveIntegerField(default=30)),
            ],
            options={
                'verbose_name': 'Valores por defecto para Periodo Escolar',
                'verbose_name_plural': 'Valores por defecto para Periodos Escolares',
            },
        ),
        migrations.AlterModelOptions(
            name='periodoescolar',
            options={'verbose_name': 'Periodo Escolar', 'verbose_name_plural': 'Periodos Escolares'},
        ),
    ]
