# Generated by Django 5.2.1 on 2025-08-07 02:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_academicos', '0016_valorespordefectoperiodo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valorespordefectoperiodo',
            options={},
        ),
        migrations.RemoveField(
            model_name='valorespordefectoperiodo',
            name='nombre_periodo',
        ),
        migrations.RemoveField(
            model_name='valorespordefectoperiodo',
            name='vacaciones_duracion_dias',
        ),
        migrations.RemoveField(
            model_name='valorespordefectoperiodo',
            name='vacaciones_inicio_dias',
        ),
        migrations.AddField(
            model_name='valorespordefectoperiodo',
            name='fecha_fin_base',
            field=models.DateField(default=datetime.date(2025, 6, 30), help_text='Fecha final del periodo por defecto'),
        ),
        migrations.AddField(
            model_name='valorespordefectoperiodo',
            name='fecha_inicio_base',
            field=models.DateField(default=datetime.date(2025, 1, 1), help_text='Fecha inicial del periodo por defecto'),
        ),
        migrations.AddField(
            model_name='valorespordefectoperiodo',
            name='fin_vacaciones_base',
            field=models.DateField(default=datetime.date(2025, 7, 31), help_text='Fecha fin vacaciones (por defecto)'),
        ),
        migrations.AddField(
            model_name='valorespordefectoperiodo',
            name='inicio_vacaciones_base',
            field=models.DateField(default=datetime.date(2025, 7, 1), help_text='Fecha inicio vacaciones (por defecto)'),
        ),
        migrations.AddField(
            model_name='valorespordefectoperiodo',
            name='nombre_periodo_fin',
            field=models.CharField(default='JUNIO', max_length=20),
        ),
        migrations.AddField(
            model_name='valorespordefectoperiodo',
            name='nombre_periodo_inicio',
            field=models.CharField(default='ENERO', max_length=20),
        ),
    ]
