# Generated by Django 5.2.1 on 2025-08-07 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos_academicos', '0017_alter_valorespordefectoperiodo_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='periodoescolar',
            unique_together=set(),
        ),
    ]
