# Generated by Django 5.2.1 on 2025-08-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_academicos', '0018_alter_periodoescolar_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ValoresPorDefectoPeriodo',
        ),
        migrations.AddField(
            model_name='periodoescolar',
            name='activo',
            field=models.BooleanField(default=False, help_text='Indica si este periodo es el vigente (solo uno puede ser True).'),
        ),
    ]
