# Generated by Django 5.2.1 on 2025-09-23 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_academicos', '0019_delete_valorespordefectoperiodo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='periodoescolar',
            name='activo',
            field=models.BooleanField(default=False, help_text='Solo puede haber un periodo activo que contenga la fecha actual.'),
        ),
        migrations.DeleteModel(
            name='TipoMateria',
        ),
    ]
