# Generated by Django 5.2.1 on 2025-09-23 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_academicos', '0020_remove_materia_tipo_alter_periodoescolar_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='tipo',
            field=models.CharField(choices=[('Obligatoria', 'Obligatoria'), ('Especialidad', 'Especialidad')], default='Obligatoria', max_length=20),
        ),
    ]
