# Generated by Django 5.2.1 on 2025-09-23 01:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_academicos', '0021_materia_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='semestre',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
