# Generated by Django 5.2.1 on 2025-09-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_academicos', '0022_alter_materia_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='acreditacion',
            field=models.CharField(choices=[('Ordinario', 'Ordinario'), ('Convalidación', 'Convalidación'), ('Equivalencia', 'Equivalencia'), ('Traslado', 'Traslado'), ('Extraordinario', 'Extraordinario')], default='Ordinario', max_length=20),
        ),
    ]
