# Generated by Django 5.2.1 on 2025-09-23 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_academicos', '0023_alter_calificacion_acreditacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='estatus',
            field=models.CharField(choices=[('Inscrito', 'Inscrito'), ('No Inscrito', 'No Inscrito'), ('Egresado', 'Egresado'), ('Titulado', 'Titulado'), ('Baja definitiva', 'Baja definitiva'), ('Baja temporal', 'Baja temporal')], default='Inscrito', max_length=20),
        ),
    ]
