# Generated by Django 5.2.1 on 2025-09-23 08:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_academicos', '0024_alumno_activo_alter_alumno_estatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='carrera',
        ),
        migrations.AddField(
            model_name='materia',
            name='carreras',
            field=models.ManyToManyField(blank=True, related_name='materias', to='datos_academicos.carrera'),
        ),
        migrations.AddField(
            model_name='materia',
            name='cuenta_promedio',
            field=models.BooleanField(default=True, help_text='Si esta materia cuenta para el cálculo del promedio general'),
        ),
        migrations.AddField(
            model_name='materia',
            name='es_universal',
            field=models.BooleanField(default=False, help_text='Si es una materia universal (servicio social, residencia, etc.)'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='semestre',
            field=models.IntegerField(blank=True, default=1, help_text='Semestre para materias obligatorias. Null para materias de especialidad y universales', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='materia',
            name='tipo',
            field=models.CharField(choices=[('Obligatoria', 'Obligatoria'), ('Especialidad', 'Especialidad'), ('Universal', 'Universal'), ('Actividad', 'Actividad')], default='Obligatoria', max_length=20),
        ),
    ]
