# Generated by Django 5.2.1 on 2025-09-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_academicos', '0026_migrate_carrera_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='semestre',
            field=models.IntegerField(blank=True, default=1, help_text='Semestre para materias obligatorias. Null para materias de especialidad y universales', null=True),
        ),
    ]
