# Generated by Django 5.2.1 on 2025-09-23 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_academicos', '0027_alter_materia_semestre'),
    ]

    operations = [
        # Primero crear el modelo MateriaCarrera
        migrations.CreateModel(
            name='MateriaCarrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.IntegerField(blank=True, help_text='Semestre específico para esta carrera. Null para materias de especialidad y universales', null=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos_academicos.carrera')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos_academicos.materia')),
            ],
            options={
                'verbose_name': 'Materia por Carrera',
                'verbose_name_plural': 'Materias por Carrera',
                'unique_together': {('materia', 'carrera')},
            },
        ),
    ]