# Generated by Django 5.2.1 on 2025-09-23 09:36

from django.db import migrations


def migrate_materia_carrera_data(apps, schema_editor):
    """
    Migra los datos existentes de la relación many-to-many entre Materia y Carrera
    al nuevo modelo MateriaCarrera, preservando el semestre de cada materia.
    """
    Materia = apps.get_model('datos_academicos', 'Materia')
    MateriaCarrera = apps.get_model('datos_academicos', 'MateriaCarrera')
    
    # Obtener todas las materias con sus carreras y semestres
    for materia in Materia.objects.all():
        semestre = materia.semestre
        
        # Para cada carrera asociada a esta materia
        for carrera in materia.carreras.all():
            # Crear la relación en MateriaCarrera
            MateriaCarrera.objects.get_or_create(
                materia=materia,
                carrera=carrera,
                defaults={'semestre': semestre}
            )


def reverse_migrate_materia_carrera_data(apps, schema_editor):
    """
    Función de reversión - elimina todos los registros de MateriaCarrera
    """
    MateriaCarrera = apps.get_model('datos_academicos', 'MateriaCarrera')
    MateriaCarrera.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('datos_academicos', '0028_create_materiacarrera_model'),
    ]

    operations = [
        migrations.RunPython(
            migrate_materia_carrera_data,
            reverse_migrate_materia_carrera_data
        ),
    ]