# Generated by Django 5.2.1 on 2025-09-23 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos_academicos', '0029_migrate_materia_data'),
    ]

    operations = [
        # Remover el campo semestre de Materia
        migrations.RemoveField(
            model_name='materia',
            name='semestre',
        ),
        # Remover el campo carreras original (many-to-many sin through)
        migrations.RemoveField(
            model_name='materia',
            name='carreras',
        ),
    ]