# Generated by Django 5.2.1 on 2025-09-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_academicos', '0030_remove_old_carreras_field'),
    ]

    operations = [
        # Agregar el nuevo campo carreras con through
        migrations.AddField(
            model_name='materia',
            name='carreras',
            field=models.ManyToManyField(
                blank=True, 
                related_name='materias', 
                through='datos_academicos.MateriaCarrera', 
                to='datos_academicos.carrera'
            ),
        ),
    ]