# Generated by Django 5.2.1 on 2025-09-23 09:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_academicos', '0031_add_new_carreras_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='creditos_totales',
            field=models.IntegerField(default=0, help_text='Créditos totales requeridos para completar la carrera', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)]),
        ),
    ]
