# Generated by Django 5.2.1 on 2025-09-24 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_academicos', '0033_inscripcion_productonoconforme_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscripcionSimple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=20, unique=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=20)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre(s)')),
                ('apellido_paterno', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido Materno')),
                ('curp', models.CharField(max_length=18, unique=True, verbose_name='CURP')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('modalidad', models.CharField(choices=[('A', 'Presencial'), ('B', 'Sabatino')], default='A', max_length=1, verbose_name='Modalidad')),
                ('escuela_procedencia', models.CharField(max_length=200, verbose_name='Escuela de Procedencia')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('alumno_creado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscripcion_simple_origen', to='datos_academicos.alumno')),
                ('carrera_solicitada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_simples', to='datos_academicos.carrera', verbose_name='Carrera Solicitada')),
            ],
            options={
                'verbose_name': 'Inscripción Simple',
                'verbose_name_plural': 'Inscripciones Simples',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
