# Generated by Django 5.2.1 on 2025-09-24 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos_academicos', '0034_inscripcionsimple'),
    ]

    operations = [
        # Eliminar tablas de productos no conformes
        migrations.RunSQL(
            "DROP TABLE IF EXISTS datos_academicos_documentoproductonoconforme;",
            reverse_sql="-- No reverse operation"
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS datos_academicos_seguimientoproductonoconforme;",
            reverse_sql="-- No reverse operation"
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS datos_academicos_productonoconforme;",
            reverse_sql="-- No reverse operation"
        ),
    ]
