# Generated by Django 5.2.1 on 2025-09-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_academicos', '0035_remove_producto_no_conforme_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcionsimple',
            name='calle',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Calle'),
        ),
        migrations.AddField(
            model_name='inscripcionsimple',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Código Postal'),
        ),
        migrations.AddField(
            model_name='inscripcionsimple',
            name='colonia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Colonia'),
        ),
        migrations.AddField(
            model_name='inscripcionsimple',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Viudo', 'Viudo')], max_length=20, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AddField(
            model_name='inscripcionsimple',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='inscripcionsimple',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='inscripcionsimple',
            name='nss',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='NSS'),
        ),
        migrations.AddField(
            model_name='inscripcionsimple',
            name='numero_exterior',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número Exterior'),
        ),
        migrations.AddField(
            model_name='inscripcionsimple',
            name='numero_interior',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número Interior'),
        ),
        migrations.AddField(
            model_name='inscripcionsimple',
            name='promedio_anterior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Promedio Anterior'),
        ),
        migrations.AddField(
            model_name='inscripcionsimple',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='RFC'),
        ),
        migrations.AddField(
            model_name='inscripcionsimple',
            name='semestre_ingreso',
            field=models.IntegerField(default=1, verbose_name='Semestre de Ingreso'),
        ),
        migrations.AddField(
            model_name='inscripcionsimple',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='inscripcionsimple',
            name='zona_procedencia',
            field=models.CharField(blank=True, choices=[('Urbana', 'Urbana'), ('Rural', 'Rural')], max_length=100, null=True, verbose_name='Zona de Procedencia'),
        ),
        migrations.AlterField(
            model_name='inscripcionsimple',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado'),
        ),
    ]
