# Generated by Django 5.2.1 on 2025-09-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_academicos', '0036_add_inscripcion_simple_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='usuario_aprobacion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
