# Generated by Django 5.2.1 on 2025-09-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_academicos', '0037_remove_productonoconforme_alumno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productonoconforme',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='productonoconforme',
            name='asignado_a',
        ),
        migrations.RemoveField(
            model_name='productonoconforme',
            name='detectado_por',
        ),
        migrations.RemoveField(
            model_name='productonoconforme',
            name='reinscripcion',
        ),
        migrations.RemoveField(
            model_name='seguimientoproductonoconforme',
            name='producto_no_conforme',
        ),
        migrations.RemoveField(
            model_name='seguimientoproductonoconforme',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='reinscripcion',
            name='carta_motivos',
            field=models.FileField(blank=True, null=True, upload_to='reinscripciones/cartas_motivos/', verbose_name='Carta de Motivos'),
        ),
        migrations.AlterField(
            model_name='reinscripcion',
            name='comprobante_pago',
            field=models.FileField(blank=True, null=True, upload_to='reinscripciones/comprobantes_pago/', verbose_name='Comprobante de Pago'),
        ),
        migrations.AlterField(
            model_name='reinscripcion',
            name='documentos_actualizados',
            field=models.FileField(blank=True, null=True, upload_to='reinscripciones/documentos_actualizados/', verbose_name='Documentos Actualizados'),
        ),
        migrations.AlterField(
            model_name='reinscripcion',
            name='motivo',
            field=models.CharField(choices=[('Baja Temporal', 'Baja Temporal'), ('Cambio de Modalidad', 'Cambio de Modalidad'), ('Cambio de Carrera', 'Cambio de Carrera'), ('Cambio de Semestre', 'Cambio de Semestre'), ('Reactivación', 'Reactivación'), ('Producto No Conforme', 'Producto No Conforme')], max_length=30),
        ),
        migrations.DeleteModel(
            name='DocumentoProductoNoConforme',
        ),
        migrations.DeleteModel(
            name='ProductoNoConforme',
        ),
        migrations.DeleteModel(
            name='SeguimientoProductoNoConforme',
        ),
    ]
