# Generated by Django 5.2.1 on 2025-09-24 11:32

from django.db import migrations


def fix_file_fields(apps, schema_editor):
    """
    Limpia los campos de archivo que tienen valores booleanos inconsistentes.
    """
    db_alias = schema_editor.connection.alias
    
    # Usar SQL directo para limpiar los datos
    with schema_editor.connection.cursor() as cursor:
        # Primero, cambiar temporalmente los campos a varchar para poder limpiarlos
        cursor.execute("""
            ALTER TABLE datos_academicos_reinscripcion 
            ALTER COLUMN carta_motivos TYPE varchar(100) USING carta_motivos::text;
        """)
        
        cursor.execute("""
            ALTER TABLE datos_academicos_reinscripcion 
            ALTER COLUMN documentos_actualizados TYPE varchar(100) USING documentos_actualizados::text;
        """)
        
        cursor.execute("""
            ALTER TABLE datos_academicos_reinscripcion 
            ALTER COLUMN comprobante_pago TYPE varchar(100) USING comprobante_pago::text;
        """)
        
        # Limpiar los valores booleanos
        cursor.execute("""
            UPDATE datos_academicos_reinscripcion 
            SET 
                carta_motivos = '',
                documentos_actualizados = '',
                comprobante_pago = ''
            WHERE 
                carta_motivos IN ('True', 'False', 't', 'f', '1', '0', 'true', 'false') OR
                documentos_actualizados IN ('True', 'False', 't', 'f', '1', '0', 'true', 'false') OR
                comprobante_pago IN ('True', 'False', 't', 'f', '1', '0', 'true', 'false');
        """)


def reverse_fix_file_fields(apps, schema_editor):
    """
    Operación reversa (no hacer nada).
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('datos_academicos', '0038_remove_productonoconforme_alumno_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_file_fields, reverse_fix_file_fields),
    ]
