# Generated by Django 5.2.1 on 2025-10-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_academicos', '0039_auto_20250924_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodoescolar',
            name='inscripcion_habilitada',
            field=models.BooleanField(default=True, help_text='Permite registrar nuevas inscripciones en este periodo'),
        ),
        migrations.AddField(
            model_name='periodoescolar',
            name='reinscripcion_habilitada',
            field=models.BooleanField(default=True, help_text='Permite registrar reinscripciones en este periodo'),
        ),
    ]
