# Generated by Django 5.2.1 on 2025-10-22 06:16

import datos_academicos.models_inscripcion_nueva
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_academicos', '0040_periodoescolar_inscripcion_habilitada_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InscripcionNueva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(default=datos_academicos.models_inscripcion_nueva.generar_folio, max_length=32, unique=True)),
                ('estado', models.CharField(choices=[('Borrador', 'Borrador'), ('Enviado', 'Enviado'), ('En Revisión', 'En Revisión'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada'), ('Completada', 'Completada')], default='Borrador', max_length=16)),
                ('nombre', models.CharField(max_length=80)),
                ('apellido_paterno', models.CharField(max_length=80)),
                ('apellido_materno', models.CharField(blank=True, max_length=80)),
                ('curp', models.CharField(max_length=18)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('modalidad', models.CharField(blank=True, max_length=32)),
                ('turno', models.CharField(blank=True, max_length=32)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comprobante_pago', models.FileField(blank=True, null=True, upload_to='inscripciones/comprobantes/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('observaciones', models.TextField(blank=True)),
                ('carrera_solicitada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datos_academicos.carrera')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('periodo_escolar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datos_academicos.periodoescolar')),
            ],
            options={
                'verbose_name': 'Inscripción (Nuevo Proceso)',
                'verbose_name_plural': 'Inscripciones (Nuevo Proceso)',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoInscripcionNueva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Identificacion', 'Identificación oficial'), ('CURP', 'CURP'), ('Certificado', 'Certificado de estudios'), ('Fotografia', 'Fotografía'), ('Otro', 'Otro')], max_length=32)),
                ('archivo', models.FileField(upload_to='inscripciones/documentos/')),
                ('notas', models.CharField(blank=True, max_length=255)),
                ('cargado_en', models.DateTimeField(auto_now_add=True)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='datos_academicos.inscripcionnueva')),
            ],
            options={
                'verbose_name': 'Documento de inscripción (Nuevo)',
                'verbose_name_plural': 'Documentos de inscripción (Nuevo)',
                'ordering': ['-cargado_en'],
            },
        ),
    ]
