# Generated by Django 5.2.1 on 2025-10-23 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_academicos', '0041_inscripcionnueva_documentoinscripcionnueva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoinscripcionnueva',
            name='tipo',
            field=models.CharField(choices=[('SOLICITUD', 'Solicitud'), ('FOTO', 'Fotografía'), ('ACTA_NAC', 'Acta de Nacimiento'), ('CURP', 'CURP'), ('CERT_PREPA', 'Certificado de Preparatoria'), ('CERT_MEDICO', 'Certificado Médico'), ('NO_ANTEC_PENALES', 'Carta de No Antecedentes Penales'), ('NSS', 'Número de Seguro Social'), ('RENUNCIA_SEG', 'Renuncia Seguro'), ('CONST_LAB', 'Constancia Laboral')], max_length=32),
        ),
        migrations.CreateModel(
            name='PagoInscripcionConcepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(choices=[('FICHA', 'Ficha'), ('INSCRIPCION', 'Inscripción'), ('PROPEDEUTICO', 'Propedéutico'), ('CREDENCIAL', 'Credencial'), ('SEGURO', 'Seguro')], max_length=32)),
                ('estado', models.CharField(choices=[('pagado', 'Pagado'), ('condonacion', 'Condonación'), ('no_aplica', 'No aplica'), ('pendiente', 'Pendiente')], default='pendiente', max_length=16)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='inscripciones/comprobantes/')),
                ('notas', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='datos_academicos.inscripcionnueva')),
            ],
            options={
                'verbose_name': 'Pago de inscripción por concepto',
                'verbose_name_plural': 'Pagos de inscripción por concepto',
                'ordering': ['concepto'],
                'unique_together': {('inscripcion', 'concepto')},
            },
        ),
    ]
