# Generated by Django 5.2.1 on 2025-10-28 05:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_academicos', '0042_alter_documentoinscripcionnueva_tipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Borrador', 'Borrador'), ('Confirmada', 'Confirmada')], default='Borrador', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas_academicas', to='datos_academicos.alumno')),
                ('confirmada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('periodo_escolar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas_academicas', to='datos_academicos.periodoescolar')),
            ],
            options={
                'verbose_name': 'Carga Académica',
                'verbose_name_plural': 'Cargas Académicas',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('alumno', 'periodo_escolar')},
            },
        ),
        migrations.CreateModel(
            name='ReinscripcionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reinscripcion_logs', to='datos_academicos.alumno')),
                ('reinscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='datos_academicos.reinscripcion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Reinscripción',
                'verbose_name_plural': 'Logs de Reinscripción',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='CargaAcademicaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adelantada', models.BooleanField(default=False, help_text='Materia asignada por adelantado respecto al mapa curricular')),
                ('semestre_asignado', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(19)])),
                ('notas', models.TextField(blank=True, null=True)),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='datos_academicos.cargaacademica')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos_academicos.materia')),
            ],
            options={
                'verbose_name': 'Materia de Carga',
                'verbose_name_plural': 'Materias de Carga',
                'unique_together': {('carga', 'materia')},
            },
        ),
    ]
