# Generated by Django 5.2.1 on 2025-10-28 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_academicos', '0045_deduplicate_reinscripcion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE datos_academicos_reinscripcion "
                        "DROP COLUMN IF EXISTS fecha_aprobacion"
                    ),
                    reverse_sql=(
                        "ALTER TABLE datos_academicos_reinscripcion "
                        "ADD COLUMN fecha_aprobacion TIMESTAMP NULL"
                    ),
                )
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='reinscripcion',
                    name='fecha_aprobacion',
                )
            ],
        ),
        migrations.AddField(
            model_name='reinscripcion',
            name='carga_academica_pdf',
            field=models.FileField(blank=True, null=True, upload_to='reinscripciones/carga_pdfs/'),
        ),
        migrations.CreateModel(
            name='ReinscripcionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=120)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='reinscripciones/pagos/')),
                ('condonado', models.BooleanField(default=False)),
                ('motivo_condonacion', models.TextField(blank=True, null=True)),
                ('validado', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('reinscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='datos_academicos.reinscripcion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago de Reinscripción',
                'verbose_name_plural': 'Pagos de Reinscripción',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
