# Generated by Django 5.2.1 on 2025-10-30 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=12)),
                ('object_id', models.CharField(max_length=64)),
                ('app_label', models.CharField(max_length=64)),
                ('model_name', models.CharField(max_length=64)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('actor_id', models.IntegerField(blank=True, null=True)),
                ('actor_username', models.CharField(blank=True, max_length=150, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, max_length=64, null=True)),
                ('source', models.CharField(blank=True, max_length=24, null=True)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id', 'created_at'], name='audit_audit_content_a80faa_idx'), models.Index(fields=['app_label', 'model_name'], name='audit_audit_app_lab_a84053_idx'), models.Index(fields=['actor_id'], name='audit_audit_actor_i_17b775_idx')],
            },
        ),
    ]
