# Generated by Django 5.2.1 on 2025-09-29 06:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoAdmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Admisión 2025', max_length=100)),
                ('año', models.IntegerField(default=2025)),
                ('fecha_inicio', models.DateTimeField(help_text='Fecha y hora de apertura del proceso')),
                ('fecha_fin', models.DateTimeField(help_text='Fecha y hora de cierre del proceso')),
                ('activo', models.BooleanField(default=False, help_text='Solo puede haber un período activo')),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Período de Admisión',
                'verbose_name_plural': 'Períodos de Admisión',
                'ordering': ['-año', '-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionAdmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50, unique=True)),
                ('valor', models.TextField()),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Admisión',
                'verbose_name_plural': 'Configuraciones de Admisión',
            },
        ),
        migrations.CreateModel(
            name='FormularioAdmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Formulario de Admisión', max_length=100)),
                ('estructura_json', models.JSONField(help_text='Estructura del formulario en formato JSON con campos, tipos y validaciones')),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('periodo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='formulario', to='admision.periodoadmision')),
            ],
            options={
                'verbose_name': 'Formulario de Admisión',
                'verbose_name_plural': 'Formularios de Admisión',
            },
        ),
        migrations.CreateModel(
            name='SolicitudAdmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('curp', models.CharField(help_text='Clave Única de Registro de Población', max_length=18, validators=[django.core.validators.RegexValidator(message='CURP debe tener el formato válido de 18 caracteres', regex='^[A-Z]{4}[0-9]{6}[HM][A-Z]{5}[0-9A-Z][0-9]$')])),
                ('email', models.EmailField(help_text='Correo electrónico para notificaciones', max_length=254)),
                ('respuestas_json', models.JSONField(help_text='Respuestas del aspirante en formato JSON')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('ip_registro', models.GenericIPAddressField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('en_revision', 'En Revisión'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='borrador', max_length=20)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='admision.periodoadmision')),
            ],
            options={
                'verbose_name': 'Solicitud de Admisión',
                'verbose_name_plural': 'Solicitudes de Admisión',
                'ordering': ['-fecha_registro'],
                'unique_together': {('curp', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='FichaAdmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ficha', models.CharField(editable=False, max_length=20, unique=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='fichas_admision/')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('email_enviado', models.BooleanField(default=False)),
                ('fecha_envio_email', models.DateTimeField(blank=True, null=True)),
                ('generada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha', to='admision.solicitudadmision')),
            ],
            options={
                'verbose_name': 'Ficha de Admisión',
                'verbose_name_plural': 'Fichas de Admisión',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
