# Generated by Django 5.2.1 on 2025-09-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admision', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodoadmision',
            name='formulario_base',
            field=models.JSONField(default=dict, help_text='Estructura base del formulario específico para este proceso de admisión'),
        ),
    ]
