# Generated by Django 5.2.1 on 2025-10-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admision', '0002_periodoadmision_formulario_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodoadmision',
            name='formulario_base',
            field=models.JSONField(blank=True, default=None, help_text='(Opcional) Estructura base del formulario específico para este proceso de admisión', null=True),
        ),
        migrations.AlterField(
            model_name='solicitudadmision',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('en_revision', 'En Revisión'), ('aceptada', 'Aceptada'), ('seleccionado', 'Seleccionado'), ('no_seleccionado', 'No seleccionado'), ('rechazada', 'Rechazada')], default='borrador', max_length=20),
        ),
    ]
