# Generated by Django 5.2.1 on 2025-10-30 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admision', '0003_alter_periodoadmision_formulario_base_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudEstadoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('en_revision', 'En Revisión'), ('aceptada', 'Aceptada'), ('seleccionado', 'Seleccionado'), ('no_seleccionado', 'No seleccionado'), ('rechazada', 'Rechazada')], max_length=20)),
                ('nuevo_estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('en_revision', 'En Revisión'), ('aceptada', 'Aceptada'), ('seleccionado', 'Seleccionado'), ('no_seleccionado', 'No seleccionado'), ('rechazada', 'Rechazada')], max_length=20)),
                ('comentario', models.TextField(blank=True)),
                ('notificacion_enviada', models.BooleanField(default=False)),
                ('resultado_notificacion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado_logs', to='admision.solicitudadmision')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Estado de Solicitud',
                'verbose_name_plural': 'Logs de Estado de Solicitud',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='admision_adjuntos/')),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='admision.solicitudadmision')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjuntos', to='admision.solicitudestadolog')),
            ],
            options={
                'verbose_name': 'Adjunto de Solicitud',
                'verbose_name_plural': 'Adjuntos de Solicitud',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
