# Generated by Django 5.2.1 on 2025-07-11 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datos_academicos', '0010_alumno_creditos_aprobados_alumno_creditos_totales_and_more'),
        ('docsbuilder', '0006_remove_variableplantilla_modelo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('constancia', 'Constancia'), ('kardex', 'Kardex'), ('boleta', 'Boleta')], max_length=50)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_procesado', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(default='Pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramites', to='datos_academicos.alumno')),
                ('plantilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docsbuilder.plantilla')),
            ],
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(max_length=100)),
                ('comentario', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacoras', to='procedimientos.tramite')),
            ],
        ),
    ]
