# Generated by Django 5.2.1 on 2025-09-23 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_academicos', '0032_carrera_creditos_totales'),
        ('procedimientos', '0002_proceso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletas', to='datos_academicos.alumno')),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('periodo_escolar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletas', to='datos_academicos.periodoescolar')),
            ],
            options={
                'verbose_name': 'Boleta de Calificaciones',
                'verbose_name_plural': 'Boletas de Calificaciones',
                'ordering': ['-fecha_generacion'],
                'unique_together': {('alumno', 'periodo_escolar')},
            },
        ),
    ]
