# Generated by Django 5.2.1 on 2025-10-29 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_academicos', '0046_remove_reinscripcion_fecha_aprobacion_and_more'),
        ('procedimientos', '0003_boleta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=200)),
                ('proyecto', models.CharField(max_length=200)),
                ('asesor_interno', models.CharField(max_length=150)),
                ('asesor_externo', models.CharField(blank=True, max_length=150)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('horas_programadas', models.PositiveIntegerField(blank=True, null=True)),
                ('horas_cumplidas', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('SOLICITADA', 'Solicitada'), ('EN_CURSO', 'En curso'), ('CONCLUIDA', 'Concluida'), ('APROBADA', 'Aprobada'), ('REPROBADA', 'Reprobada')], default='SOLICITADA', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residencias', to='datos_academicos.alumno')),
                ('periodo_escolar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residencias', to='datos_academicos.periodoescolar')),
            ],
            options={
                'verbose_name': 'Residencia Profesional',
                'verbose_name_plural': 'Residencias Profesionales',
                'ordering': ['-creado'],
                'unique_together': {('alumno', 'proyecto')},
            },
        ),
        migrations.CreateModel(
            name='ResidenciaBitacoraEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('actividad', models.TextField()),
                ('horas', models.PositiveIntegerField(default=0)),
                ('evidencia', models.CharField(blank=True, max_length=255)),
                ('hoja', models.CharField(blank=True, max_length=100)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('residencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacora', to='procedimientos.residencia')),
            ],
            options={
                'verbose_name': 'Entrada de Bitácora de Residencia',
                'verbose_name_plural': 'Entradas de Bitácora de Residencia',
                'ordering': ['-fecha', '-creado'],
            },
        ),
    ]
